# Generated by Django 5.2.8 on 2025-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the reward', max_length=64, unique=True)),
                ('base_coins', models.IntegerField(default=10, help_text='Base amount of coins')),
                ('description', models.TextField(default='', help_text='Description of this reward')),
            ],
            options={
                'db_table': 'coinreward',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Amount of coins (positive for gain, negative for loss)')),
                ('reason', models.CharField(help_text='Reason for transaction', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cointransaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the pack', max_length=255)),
                ('cost', models.IntegerField(default=0, help_text='Cost in coins to purchase this pack')),
                ('description', models.TextField(default='', help_text='Description of pack contents')),
                ('emoji', models.CharField(default='📦', help_text='Emoji for this pack', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this pack can be purchased')),
            ],
            options={
                'db_table': 'pack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_id', models.IntegerField(help_text='Ball ID (NBA collectible)')),
                ('rarity', models.FloatField(default=1.0, help_text='Rarity/probability (0.0 to 1.0)')),
            ],
            options={
                'db_table': 'pack_content',
                'managed': False,
            },
        ),
    ]
