# Generated by Django 5.2.8 on 2025-11-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pack name (e.g., Common, Rare)', max_length=64, unique=True)),
                ('cost', models.IntegerField(help_text='Coin cost to buy this pack')),
                ('description', models.TextField(help_text='Pack description for /packs info command')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this pack can be purchased')),
            ],
            options={
                'db_table': 'pack',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.BigIntegerField(default=0, help_text="Player's coin balance"),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Coin amount (positive for gain, negative for loss)')),
                ('reason', models.CharField(help_text="Why coins were gained/lost (e.g., 'Pack Purchase')", max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bd_models.player')),
            ],
            options={
                'db_table': 'cointransaction',
                'managed': True,
                'indexes': [models.Index(fields=['player'], name='cointransac_player__6b22aa_idx')],
            },
        ),
    ]
