# Generated by Django 5.2.8 on 2025-11-23 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pack name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Pack description')),
                ('cost', models.IntegerField(help_text='Cost in coins')),
                ('enabled', models.BooleanField(default=True, help_text='Whether pack is available for purchase')),
            ],
            options={
                'db_table': 'pack',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=0, help_text='Player coin balance'),
        ),
        migrations.CreateModel(
            name='PackReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, help_text='Rarity weight (higher = more common)')),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='bd_models.pack')),
            ],
            options={
                'db_table': 'packreward',
                'managed': True,
                'unique_together': {('pack', 'ball')},
            },
        ),
        migrations.CreateModel(
            name='PlayerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Number of packs owned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.pack')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='bd_models.player')),
            ],
            options={
                'db_table': 'playerpack',
                'managed': True,
                'unique_together': {('player', 'pack')},
            },
        ),
    ]
